#!/usr/bin/env bash
#
# This script analyzes tables in all databases, or a specified database.
# It uses the `mariadb-check` command with the `--analyze` option
#

set -e -o pipefail
[ "$DEBUG" == 'true' ] && set -x
# shellcheck disable=SC1090
. "$(dirname "${0}")/common.sh"

wait_mariadb

if [ -z "$1" ]; then
    DATABASES=$($MYSQL -rs -e "SHOW DATABASES" | grep -v -E '(cloudsqladmin|information_schema|performance_schema)')
else
    DATABASES=$*
fi

# Perform the analysis
echo -n "Analyzing..."
for DB in $DATABASES; do
    echo -n " $DB"
    $MYCHECK --analyze ${DB}
done
echo ". Done."

echo "Finished."
