#!/usr/bin/env bash

set -e -o pipefail
[ "$DEBUG" == 'true' ] && set -x
. "$(dirname $0)/"common.sh

if [ -z "$BACKUP_DIR" ]; then
    echo "BACKUP_DIR not set"
    exit 128
fi

wait_mariadb

MYSQL="mysql ${MYCONN}"
GZIP="gzip --fast"
MYDUMP="mysqldump ${MYCONN}"
BACKUP_PATH="${BACKUP_DIR}/$(date +%Y%m%d%H%M)"
RETENTION_DAYS=${RETENTION_DAYS-14}

if [ -z "$1" ]; then
    DATABASES=$($MYSQL -rs -e "SHOW DATABASES" | grep -v -E '(information_schema|performance_schema)')
else
    DATABASES=$@
fi

# Perform the backup
mkdir -p "$BACKUP_PATH"
echo -n "Dumping..."
for DB in $DATABASES; do
    echo -n " $DB"
    $MYDUMP --opt --single-transaction --flush-logs --events --databases ${DB} | $GZIP > "${BACKUP_PATH}/${DB}.sql.gz"
done
echo ". Done."

# Delete expired backups
echo -n "Cleanup... "
find ${BACKUP_DIR} -name "*.sql.gz" -mtime +$RETENTION_DAYS -exec rm -f {} \;
find ${BACKUP_DIR} -type d -empty -delete
echo "Done."
