#!/usr/bin/env bash

set -e -o pipefail
[ "$DEBUG" == 'true' ] && set -x
. "$(dirname $0)/"common.sh

wait_mariadb

if [ -z "$1" ]; then
    DATABASES=$($MYSQL -rs -e "SHOW DATABASES" | grep -v -E '(information_schema|performance_schema)')
else
    DATABASES=$@
fi

# Perform the check
echo -n "Checking..."
for DB in $DATABASES; do
    echo -n " $DB"
    $MYCHECK --auto-repair ${DB}
done
echo ". Done."

echo "Finished."
