#!/usr/bin/env bash 

set -e -o pipefail
[ "$DEBUG" == 'true' ] && set -x
. "$(dirname $0)/"common.sh

wait_mariadb

DATABASES=$@

# Convert to Innodb
for DB in $DATABASES; do
    TO_CONVERT=$(echo "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = \"$DB\" AND ENGINE = 'MyISAM';" | $MYSQL --skip-column-names)
    echo -n "Converting $TO_CONVERT in $DB..."
    echo "ALTER TABLE $TO_CONVERT ENGINE=InnoDB;" | $MYSQL $DB
    echo ". Done."
done

echo "All done."
