#!/usr/bin/env bash

set -e -o pipefail
[ "$DEBUG" == 'true' ] && set -x
. "$(dirname $0)/"common.sh

if [ "$1" == '--no-delete-database' ]; then
    shift;
    DELETE_DB=false
else
    DELETE_DB=true
fi

if [ ! -z "$2" ]; then
    DB_SRC=$1
    DB_DST=$2
else
    echo "You must specify a <source> and <destination> database."
    exit 99
fi

wait_mariadb

DATA_SRC=${DATA_SRC-'/data'}

echo -n "Dumping..."
echo -n " $DB_SRC"
$MYSQLDUMP --opt --single-transaction --events ${DB_SRC} | $GZIP > "${DATA_SRC}/${DB_SRC}.sql.gz"
echo ". Done."

echo ">>> Loading Database Dump from from ${DATA_SRC}."
DUMP="${DATA_SRC}/${DB_SRC}.sql.gz"
if [ "$DELETE_DB" == 'true' ]; then
    echo -n "Deleting $DB_DST... "
    echo "DROP DATABASE IF EXISTS \`$DB_DST\`;" | $MYSQL
    echo "Done."
fi
echo -n "Loading $DB_SRC as $DB_DST... "
echo "CREATE DATABASE IF NOT EXISTS \`$DB_DST\`;" | $MYSQL
gunzip --stdout $DUMP | $MYSQL --one-database $DB_DST
echo "Done."

echo "Finished."
