#!/usr/bin/env bash

set -e -o pipefail

[ "$DEBUG" == 'true' ] && set -x

if [ "$1" == '--no-delete-database' ]; then
    shift;
    DELETE_DB=false
else
    DELETE_DB=true
fi

if [ -z "$2" ]; then
    DB_SRC=$1
    DB_DST=$2
else
    echo "You must specify a <source> and <destination> database to."
    exit 99
fi

if [ -z "${DATABASE_HOST}" ]; then
    echo -n "=> Using Docker Links for configuration "
    DATABASE_PASS=$MARIADB_ENV_MYSQL_ROOT_PASSWORD
    DATABASE_USER=root
    DATABASE_HOST=$MARIADB_PORT_3306_TCP_ADDR
    DATABASE_PORT=$MARIADB_PORT_3306_TCP_PORT
    echo "mysql://${DATABASE_HOST}:$DATABASE_PORT"
else
    echo -n  "=> Using variables for configuration "
    DATABASE_HOST=${DATABASE_HOST-localhost}
    DATABASE_PORT=${DATABASE_PORT-3306}
    echo "mysql://${DATABASE_HOST}:$DATABASE_PORT"
fi

DATA_SRC=${DATA_SRC-'/data/'}
MYSQL="mysql --host=${DATABASE_HOST} --port=${DATABASE_PORT} --user=${DATABASE_USER} --password=${DATABASE_PASS}"

echo -n "Dumping..."
echo -n " $DB_SRC"
$MYDUMP --opt --single-transaction --flush-logs --events --databases ${DB_SRC} | $GZIP > "${DATA_SRC}/${DB_SRC}.sql.gz"
echo ". Done."

echo ">>> Loading Database Dump from from ${DATA_SRC}."
$DUMP="${DATA_SRC}/${DB_SRC}.sql.gz"
if [ "$DELETE_DB" == 'true' ]; then
    echo -n "Deleting $DB_DST... "
    echo "DROP DATABASE IF EXISTS \`$DB_DST\`;" | $MYSQL
    echo "Done."
fi
echo -n "Loading $DB_SRC as $DB_DST... "
echo "CREATE DATABASE IF NOT EXISTS \`$DB_DST\`;" | $MYSQL
gunzip --stdout $DUMP | $MYSQL --one-database $DB
echo "Done."

echo "Finished."
