#!/usr/bin/env bash

set -e -o pipefail
[ "$DEBUG" == 'true' ] && set -x
. "$(dirname $0)/"common.sh

if [ "$1" == '--no-create-database' ]; then
    shift;
    CREATE_DB=false
else
    CREATE_DB=true
fi

if [ -z "$1" ]; then
    echo "User not specified"
    exit 128
fi

# Echo password if it's generated
ECHO_PASSWORD='false' && [ "$2" == '' ] && ECHO_PASSWORD='true'

NEW_USER=$1
NEW_PASS=${2-$(genpasswd 8)}

wait_mariadb

if [ "$CREATE_DB" == 'true' ]; then
    echo ">>> Creating user and database: $NEW_USER..."
else
    echo ">>> Creating user: $NEW_USER..."
fi

if [ "$CREATE_DB" == 'true' ]; then
    echo "CREATE DATABASE IF NOT EXISTS ${NEW_USER};" | $MYSQL
fi
echo "GRANT ALL ON ${NEW_USER}.* to ${NEW_USER}@'%' IDENTIFIED BY '$NEW_PASS';" | $MYSQL
[ "$ECHO_PASSWORD" == 'false' ] && NEW_PASS='********'
echo "Created: ${NEW_USER} / ${NEW_PASS}"
echo "FLUSH PRIVILEGES;" | $MYSQL
echo ">>> Finished."
