#!/usr/bin/env bash

set -e -o pipefail
[ "$DEBUG" == 'true' ] && set -x
. "$(dirname $0)/"common.sh

if [ "$1" == '--no-create-database' ]; then
    shift;
    CREATE_DB=false
else
    CREATE_DB=true
fi

if [ -z "$1" ]; then
    echo "User not specified"
    exit 128
fi

# Echo password if it's generated
ECHO_PASSWORD='false' && [ "$2" == '' ] && ECHO_PASSWORD='true'

NEW_NAME=$1
NEW_PASS=${2-$(genpasswd 16)}

wait_mariadb

if [ "$CREATE_DB" == 'true' ]; then
    echo ">>> Creating user and database: $NEW_NAME..."
else
    echo ">>> Creating user: $NEW_NAME..."
fi

if [ "$CREATE_DB" == 'true' ]; then
    echo "CREATE DATABASE IF NOT EXISTS ${NEW_NAME};" | $MYSQL
fi
# Create user first (MySQL 8 compatible)
echo "CREATE USER IF NOT EXISTS ${NEW_NAME}@'%' IDENTIFIED BY '${NEW_PASS}';" | $MYSQL
# Change the password if the user already existed
# N.B. ALTER USER is preferred, however MariaDB 10.1 and earlier don't support this
echo "SET PASSWORD FOR ${NEW_NAME}@'%' = PASSWORD('${NEW_PASS}');" | $MYSQL
# Specifiy the exact permissions. NB. This is also RDS compatible as GRANT ALL not possible.
echo "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE, EVENT, TRIGGER ON ${NEW_NAME}.* TO ${NEW_NAME}@'%';" | $MYSQL

[ "$ECHO_PASSWORD" == 'false' ] && NEW_PASS='********'
echo "Created: ${NEW_NAME} / ${NEW_PASS}"
echo "FLUSH PRIVILEGES;" | $MYSQL
echo ">>> Finished."
