#!/usr/bin/env bash

set -e

[ "$DEBUG" == 'true' ] && set -x

cat << EOF

  Please choose a command:

     backup <databases>

     check <databases>

     convert-to-innodb <databases>

     copy-database <source> <destination>

     create-user <username> <password>

     import - import dumps

     mysql - start a MySQL client session

EOF
