#!/usr/bin/env bash

set -e

[ "$DEBUG" == 'true' ] && set -x

cat << EOF

  Please choose a command:

     backup

     copy-database <source> <destination>

     create-user <username>

     convert-to-innodb <databases>

     import

     mysql - start a MySQL client session

EOF

