#!/usr/bin/env bash
# shellcheck disable=SC2034 shell=bash

set -eo pipefail
IFS=$'\n\t'

[[ "${DEBUG:-}" == 'true' ]] && set -x

# shellcheck disable=SC1090
. "$(dirname "${0}")/common.sh"

# This should be at the top but common.sh throws an error when used
set -u

# Options:
# compression gzip|lz4|bz2|zip|none
# dateformat %Y%m%d%H%M%S
# checksum sha256
# umask 0077
# dest gs://|s3://|file://
# databases ALL

parse_options() {

    # For reference these are the relevant parameters that mysql command accepts
    #   -h, --host=name     Connect to host.
    #   -p, --password[=name]
    #   -P, --port=#        Port number to use for connection or 0 for default to, in
    #   -u, --user=name     User for login if not current user.
    #   -D, --database=name Database to use.

    # We don't want to pass these back to the caller
    local password
    local password_file

    # Pull in environment variables prefixed with DATABASE_
    for item in host port user database password password_file; do
        local varname
        varname="DATABASE_${item^^}"
        if [[ -n "${!varname:-}" ]]; then
          eval ${item}="${!varname}"
        fi
    done

    # Pull in environment variables prefixed with LOAD_
    # LOAD_SKIP_DATABASES should be comma separated
    for item in compression skip_databases; do
        local varname
        varname="LOAD_${item^^}"
        if [[ -n "${!varname:-}" ]]; then
          eval ${item}="${!varname}"
        fi
    done

    # If skip_databases was set via env var, split into an array
    if [[ -n "${skip_databases:-}" ]]; then
        IFS=',' read -r -a skip_databases <<< "${skip_databases}"
    fi

    # Options and long options
    local options="h:P:u:D:p:"
    local longopts="host:,port:,user:,database:,password:,password-file:,compression:,skip-database:,umask:,sed:"
    local parsed

    # Parse with getopt (not getopts)
    ! parsed=$(getopt --quiet --options=${options} --longoptions=${longopts} --name "${0}" -- "${@}")
    eval set -- "${parsed}"
    while true; do
      case "${1}" in
        -h|--host)
          host="${2}"
          shift 2
          ;;
        -P|--port)
          port="${2}"
          shift 2
          ;;
        -u|--user)
          user="${2}"
          shift 2
          ;;
        -D|--database)
          database="${2}"
          shift 2
          ;;
        -p|--password)
          password="${2}"
          shift 2
          ;;
        --password-file)
          password_file="${2}"
          shift 2
          ;;
        --skip-database)
          skip_databases+=( "${2}" )
          shift 2
          ;;
        --compression)
          compression="${2}"
          shift 2
          ;;
        --umask)
          umask="${2}"
          shift 2
          ;;
        --sed)
          sed+=( "${2}" )
          shift 2
          ;;
        --)
          shift
          break
          ;;
        *)
          echo "Unrecognised option"
          exit 3
          ;;
      esac
    done

    # Set remaining command line arguments into an array
    args=( "${@}" )

    # Read in the password file if set
    if [[ -n "${password_file:-}" ]]; then
        # Read password file if set on the command line or DATABASE_PASSWORD_FILE
        password="$(cat "${password_file}")"
    fi

    # If the password was set write it to .my.cnf (or save a temporary file and set --defaults-extra-file)
    # Note: --defaults-extra-file must be specified first on the mysql command line
    # TODO: add trap to clean up the temp file
    if [[ -n "${password:-}" ]]; then
        local old_umask
        old_umask="$(umask)"
        umask 0077
        defaults_extra_file="$(mktemp)"
        printf "%s\n" \
          "[client]" \
          "password=${password}" > "${defaults_extra_file}"
        umask "${old_umask}"
        echoerr ">>> Password written to ${defaults_extra_file}"
    fi

    # Setup connection string
    connection=()
    for item in defaults_extra_file host port user database ; do
        if [[ -n "${!item:-}" ]]; then
          connection+=("--${item//_/-}=${!item}")
        fi
    done

    connection_no_db=()
    for item in defaults_extra_file host port user ; do
        if [[ -n "${!item:-}" ]]; then
          connection_no_db+=("--${item//_/-}=${!item}")
        fi
    done
}

parse_options "${@}"

# TODO: add `--save-local DIR` to specify a local directory to keep a local copy as well as uploading to the DEST (don't delete local after upload)
usage() {
    echoerr "Usage: ${0} [GLOBAL_OPTIONS] [OPTIONS] SOURCE DATABASE [NEW_DATABASE]"
    echoerr "Global Options: (where possible these options match mysql options)"
    echoerr "    -h|--host    host to connect to"
    echoerr "    -P|--port    post to connect to"
    echoerr "    -u|--user    user to connect with"
    echoerr "    -D|--database    database to connect to"
    echoerr "    -p|--password    password to connection to (not recommended. Use password-file)"
    echoerr "    --password-file    password file to read password from"
    echoerr ""
    echoerr "Options:"
    echoerr "    --compression    auto|gzip|lz4|bz2|none"
    echoerr "    --date-format    %Y%m%d%H%M%S"
    echoerr "    --checksum    sha256"
    echoerr "    --umask    0077"
    echoerr "    --sed"
    echoerr ""
    echoerr "    SOURCE    Source to load database dumps from. s3://, gs:// and files are supported."
    echoerr "    DATABASE    database to load to."
    echoerr "    NEW_DATABASE    database to load to."
    echoerr ""
    echoerr "Environment variables:"
    echoerr "    Any global options can be prefixed with DATABASE_ and specified via environment variable."
    echoerr "    Any save command options can be prefixed with LOAD_ and specified via environment variable."
}

case "${#args[@]}" in
  0|1)
    echo "error: Insufficient args: ${#args[@]} args passed"
    exit 1
    ;;
  2)
    source="${args[0]}"
    src_database="${args[1]}"
    dest_database="${args[1]}"
    ;;
  3)
    source="${args[0]}"
    src_database="${args[1]}"
    dest_database="${args[2]}"
    ;;
  *)
    echo "Unknown"
    exit 1
    ;;
  esac

echo "Source: ${source}"
echo "Source Database: ${src_database}"
echo "Destination Database: ${dest_database}"

# Set the umask, umask defaults to 0077 to keep files private during db dumping
umask "${umask:-0077}"

get_storage_commands "${source}"
file_path="$(eval ${find_object} "${source}" "${src_database}")"
if [[ -z "${file_path}" ]]; then
  echo "No save found for database ${src_database} in ${source}"
  exit 1
else
  echo "Filepath: ${file_path}"
fi

if [[ "${compression:-auto}" == "auto" ]]; then
  case "${file_path##*.}" in
    "lz4")
      compression="lz4"
      ;;
    "gz")
      compression="gzip"
      ;;
    "bz2")
      compression="bz2"
      ;;
    "zip")
      compression="zip"
      ;;
    "sql"|"dump"|"pgdump"|"pg_dump")
      compression="none"
      ;;
    *)
      echo "Unknown file expression, please define compression used or compression=none"
      exit 1
      ;;
    esac
fi

# Output compression
get_compression_commands "${compression}"

# Process sed filters
sed_cmd=()
for item in "${sed[@]}"; do
  sed_cmd+=( "-e" "${item}" )
done

wait_mariadb "${host}" "${port:-3306}"

/usr/bin/mysql "${connection[@]}" -rs -e "DROP DATABASE IF EXISTS ${dest_database}; CREATE DATABASE ${dest_database}"

if [[ "${#sed_cmd[@]}" -gt 0 ]]; then
  eval "${fetch_cmd[@]}" "${file_path}" "-" | "${decompression_cmd[@]}" | sed -E "${sed_cmd[@]}" | /usr/bin/mysql "${connection_no_db[@]}" "${dest_database}"
else
  eval "${fetch_cmd[@]}" "${file_path}" "-" | "${decompression_cmd[@]}" | /usr/bin/mysql "${connection_no_db[@]}" "${dest_database}"
fi

echo ">> Finished."
